-- P4 cold-start math tests (File 04 §3.1–3.4; spec-conflicts M5/L8; ADR-0005).
-- Every expected number below is derived from the SPEC constants, not from running the
-- implementation: the 240-row table comes from scripts/gen-prior-cells-expected.mjs
-- (independent recomputation of §3.2–3.3), and the alpha0/beta0 literals are hand-computed
-- in the comments where they appear. Tolerances only absorb float4 storage rounding.
begin;
create extension if not exists pgtap with schema extensions;
select no_plan();

-- ===========================================================================
-- §1 prior_cells v0 is byte-exact vs File 04 §3.2–3.3 (to float4 precision)
-- ===========================================================================
create temp table expected_prior_cells (
  chronotype_class text, category text, daypart text, day_type text,
  mu0 double precision, n0 double precision
);
-- GENERATED by scripts/gen-prior-cells-expected.mjs — do not hand-edit (240 rows)
insert into expected_prior_cells (chronotype_class, category, daypart, day_type, mu0, n0) values
    ('DE','admin','AF','weekday',0.6154540,8),
    ('DE','admin','AF','weekend',0.5827270,4),
    ('DE','admin','EM','weekday',0.4928586,8),
    ('DE','admin','EM','weekend',0.5214293,4),
    ('DE','admin','EV','weekday',0.6626236,8),
    ('DE','admin','EV','weekend',0.6063118,4),
    ('DE','admin','MD','weekday',0.5621765,8),
    ('DE','admin','MD','weekend',0.5560883,4),
    ('DE','admin','MO','weekday',0.5532920,8),
    ('DE','admin','MO','weekend',0.5516460,4),
    ('DE','admin','NT','weekday',0.6727580,8),
    ('DE','admin','NT','weekend',0.6113790,4),
    ('DE','deep','AF','weekday',0.6200000,8),
    ('DE','deep','AF','weekend',0.5850000,4),
    ('DE','deep','EM','weekday',0.3500000,8),
    ('DE','deep','EM','weekend',0.4500000,4),
    ('DE','deep','EV','weekday',0.7200000,8),
    ('DE','deep','EV','weekend',0.6350000,4),
    ('DE','deep','MD','weekday',0.5000000,8),
    ('DE','deep','MD','weekend',0.5250000,4),
    ('DE','deep','MO','weekday',0.4800000,8),
    ('DE','deep','MO','weekend',0.5150000,4),
    ('DE','deep','NT','weekday',0.7400000,8),
    ('DE','deep','NT','weekend',0.6450000,4),
    ('DE','learning','AF','weekday',0.5905201,8),
    ('DE','learning','AF','weekend',0.5702601,4),
    ('DE','learning','EM','weekday',0.3598113,8),
    ('DE','learning','EM','weekend',0.4549056,4),
    ('DE','learning','EV','weekday',0.6797868,8),
    ('DE','learning','EV','weekend',0.6148934,4),
    ('DE','learning','MD','weekday',0.4875026,8),
    ('DE','learning','MD','weekend',0.5187513,4),
    ('DE','learning','MO','weekday',0.4705251,8),
    ('DE','learning','MO','weekend',0.5102626,4),
    ('DE','learning','NT','weekday',0.6982700,8),
    ('DE','learning','NT','weekend',0.6241350,4),
    ('DE','physical','AF','weekday',0.6724422,8),
    ('DE','physical','AF','weekend',0.6112211,4),
    ('DE','physical','EM','weekday',0.4401701,8),
    ('DE','physical','EM','weekend',0.4950851,4),
    ('DE','physical','EV','weekday',0.6500943,8),
    ('DE','physical','EV','weekend',0.6000472,4),
    ('DE','physical','MD','weekday',0.5249792,8),
    ('DE','physical','MD','weekend',0.5374896,4),
    ('DE','physical','MO','weekday',0.5139905,8),
    ('DE','physical','MO','weekend',0.5319952,4),
    ('DE','physical','NT','weekday',0.6626850,8),
    ('DE','physical','NT','weekend',0.6063425,4),
    ('DM','admin','AF','weekday',0.5842638,8),
    ('DM','admin','AF','weekend',0.5671319,4),
    ('DM','admin','EM','weekday',0.6941408,8),
    ('DM','admin','EM','weekend',0.6220704,4),
    ('DM','admin','EV','weekday',0.5168788,8),
    ('DM','admin','EV','weekend',0.5334394,4),
    ('DM','admin','MD','weekday',0.5621765,8),
    ('DM','admin','MD','weekend',0.5560883,4),
    ('DM','admin','MO','weekday',0.6727580,8),
    ('DM','admin','MO','weekend',0.6113790,4),
    ('DM','admin','NT','weekday',0.4672261,8),
    ('DM','admin','NT','weekend',0.5086130,4),
    ('DM','deep','AF','weekday',0.5500000,8),
    ('DM','deep','AF','weekend',0.5500000,4),
    ('DM','deep','EM','weekday',0.7800000,8),
    ('DM','deep','EM','weekend',0.6650000,4),
    ('DM','deep','EV','weekday',0.4000000,8),
    ('DM','deep','EV','weekend',0.4750000,4),
    ('DM','deep','MD','weekday',0.5000000,8),
    ('DM','deep','MD','weekend',0.5250000,4),
    ('DM','deep','MO','weekday',0.7400000,8),
    ('DM','deep','MO','weekend',0.6450000,4),
    ('DM','deep','NT','weekday',0.3000000,8),
    ('DM','deep','NT','weekend',0.4250000,4),
    ('DM','learning','AF','weekday',0.5301061,8),
    ('DM','learning','AF','weekend',0.5400530,4),
    ('DM','learning','EM','weekday',0.7361040,8),
    ('DM','learning','EM','weekend',0.6430520,4),
    ('DM','learning','EV','weekday',0.4025995,8),
    ('DM','learning','EV','weekend',0.4762998,4),
    ('DM','learning','MD','weekday',0.4875026,8),
    ('DM','learning','MD','weekend',0.5187513,4),
    ('DM','learning','MO','weekday',0.6982700,8),
    ('DM','learning','MO','weekend',0.6241350,4),
    ('DM','learning','NT','weekday',0.3164352,8),
    ('DM','learning','NT','weekend',0.4332176,4),
    ('DM','physical','AF','weekday',0.6365379,8),
    ('DM','physical','AF','weekend',0.5932689,4),
    ('DM','physical','EM','weekday',0.6891432,8),
    ('DM','physical','EM','weekend',0.6195716,4),
    ('DM','physical','EV','weekday',0.4692873,8),
    ('DM','physical','EV','weekend',0.5096436,4),
    ('DM','physical','MD','weekday',0.5249792,8),
    ('DM','physical','MD','weekend',0.5374896,4),
    ('DM','physical','MO','weekday',0.6626850,8),
    ('DM','physical','MO','weekend',0.6063425,4),
    ('DM','physical','NT','weekday',0.4095046,8),
    ('DM','physical','NT','weekend',0.4797523,4),
    ('INT','admin','AF','weekday',0.6154540,8),
    ('INT','admin','AF','weekend',0.5827270,4),
    ('INT','admin','EM','weekday',0.5842638,8),
    ('INT','admin','EM','weekend',0.5671319,4),
    ('INT','admin','EV','weekday',0.5975454,8),
    ('INT','admin','EV','weekend',0.5737727,4),
    ('INT','admin','MD','weekday',0.5710213,8),
    ('INT','admin','MD','weekend',0.5605106,4),
    ('INT','admin','MO','weekday',0.6337834,8),
    ('INT','admin','MO','weekend',0.5918917,4),
    ('INT','admin','NT','weekday',0.5532920,8),
    ('INT','admin','NT','weekend',0.5516460,4),
    ('INT','deep','AF','weekday',0.6200000,8),
    ('INT','deep','AF','weekend',0.5850000,4),
    ('INT','deep','EM','weekday',0.5500000,8),
    ('INT','deep','EM','weekend',0.5500000,4),
    ('INT','deep','EV','weekday',0.5800000,8),
    ('INT','deep','EV','weekend',0.5650000,4),
    ('INT','deep','MD','weekday',0.5200000,8),
    ('INT','deep','MD','weekend',0.5350000,4),
    ('INT','deep','MO','weekday',0.6600000,8),
    ('INT','deep','MO','weekend',0.6050000,4),
    ('INT','deep','NT','weekday',0.4800000,8),
    ('INT','deep','NT','weekend',0.5150000,4),
    ('INT','learning','AF','weekday',0.5905201,8),
    ('INT','learning','AF','weekend',0.5702601,4),
    ('INT','learning','EM','weekday',0.5301061,8),
    ('INT','learning','EM','weekend',0.5400530,4),
    ('INT','learning','EV','weekday',0.5558552,8),
    ('INT','learning','EV','weekend',0.5529276,4),
    ('INT','learning','MD','weekday',0.5045090,8),
    ('INT','learning','MD','weekend',0.5272545,4),
    ('INT','learning','MO','weekday',0.6256969,8),
    ('INT','learning','MO','weekend',0.5878484,4),
    ('INT','learning','NT','weekday',0.4705251,8),
    ('INT','learning','NT','weekend',0.5102626,4),
    ('INT','physical','AF','weekday',0.6724422,8),
    ('INT','physical','AF','weekend',0.6112211,4),
    ('INT','physical','EM','weekday',0.5523991,8),
    ('INT','physical','EM','weekend',0.5511996,4),
    ('INT','physical','EV','weekday',0.5689394,8),
    ('INT','physical','EV','weekend',0.5594697,4),
    ('INT','physical','MD','weekday',0.5359438,8),
    ('INT','physical','MD','weekend',0.5429719,4),
    ('INT','physical','MO','weekday',0.6141551,8),
    ('INT','physical','MO','weekend',0.5820775,4),
    ('INT','physical','NT','weekday',0.5139905,8),
    ('INT','physical','NT','weekend',0.5319952,4),
    ('ME','admin','AF','weekday',0.6245518,8),
    ('ME','admin','AF','weekend',0.5872759,4),
    ('ME','admin','EM','weekday',0.5261641,8),
    ('ME','admin','EM','weekend',0.5380820,4),
    ('ME','admin','EV','weekday',0.6431810,8),
    ('ME','admin','EV','weekend',0.5965905,4),
    ('ME','admin','MD','weekday',0.5710213,8),
    ('ME','admin','MD','weekend',0.5605106,4),
    ('ME','admin','MO','weekday',0.5842638,8),
    ('ME','admin','MO','weekend',0.5671319,4),
    ('ME','admin','NT','weekday',0.6154540,8),
    ('ME','admin','NT','weekend',0.5827270,4),
    ('ME','deep','AF','weekday',0.6400000,8),
    ('ME','deep','AF','weekend',0.5950000,4),
    ('ME','deep','EM','weekday',0.4200000,8),
    ('ME','deep','EM','weekend',0.4850000,4),
    ('ME','deep','EV','weekday',0.6800000,8),
    ('ME','deep','EV','weekend',0.6150000,4),
    ('ME','deep','MD','weekday',0.5200000,8),
    ('ME','deep','MD','weekend',0.5350000,4),
    ('ME','deep','MO','weekday',0.5500000,8),
    ('ME','deep','MO','weekend',0.5500000,4),
    ('ME','deep','NT','weekday',0.6200000,8),
    ('ME','deep','NT','weekend',0.5850000,4),
    ('ME','learning','AF','weekday',0.6080349,8),
    ('ME','learning','AF','weekend',0.5790175,4),
    ('ME','learning','EM','weekday',0.4196142,8),
    ('ME','learning','EM','weekend',0.4848071,4),
    ('ME','learning','EV','weekday',0.6435271,8),
    ('ME','learning','EV','weekend',0.5967636,4),
    ('ME','learning','MD','weekday',0.5045090,8),
    ('ME','learning','MD','weekend',0.5272545,4),
    ('ME','learning','MO','weekday',0.5301061,8),
    ('ME','learning','MO','weekend',0.5400530,4),
    ('ME','learning','NT','weekday',0.5905201,8),
    ('ME','learning','NT','weekend',0.5702601,4),
    ('ME','physical','AF','weekday',0.6827525,8),
    ('ME','physical','AF','weekend',0.6163763,4),
    ('ME','physical','EM','weekday',0.4806284,8),
    ('ME','physical','EM','weekend',0.5153142,4),
    ('ME','physical','EV','weekday',0.6258782,8),
    ('ME','physical','EV','weekend',0.5879391,4),
    ('ME','physical','MD','weekday',0.5359438,8),
    ('ME','physical','MD','weekend',0.5429719,4),
    ('ME','physical','MO','weekday',0.5523991,8),
    ('ME','physical','MO','weekend',0.5511996,4),
    ('ME','physical','NT','weekday',0.5912781,8),
    ('ME','physical','NT','weekend',0.5706391,4),
    ('MM','admin','AF','weekday',0.5975454,8),
    ('MM','admin','AF','weekend',0.5737727,4),
    ('MM','admin','EM','weekday',0.6527806,8),
    ('MM','admin','EM','weekend',0.6013903,4),
    ('MM','admin','EV','weekday',0.5532920,8),
    ('MM','admin','EV','weekend',0.5516460,4),
    ('MM','admin','MD','weekday',0.5710213,8),
    ('MM','admin','MD','weekend',0.5605106,4),
    ('MM','admin','MO','weekday',0.6626236,8),
    ('MM','admin','MO','weekend',0.6063118,4),
    ('MM','admin','NT','weekday',0.4977715,8),
    ('MM','admin','NT','weekend',0.5238858,4),
    ('MM','deep','AF','weekday',0.5800000,8),
    ('MM','deep','AF','weekend',0.5650000,4),
    ('MM','deep','EM','weekday',0.7000000,8),
    ('MM','deep','EM','weekend',0.6250000,4),
    ('MM','deep','EV','weekday',0.4800000,8),
    ('MM','deep','EV','weekend',0.5150000,4),
    ('MM','deep','MD','weekday',0.5200000,8),
    ('MM','deep','MD','weekend',0.5350000,4),
    ('MM','deep','MO','weekday',0.7200000,8),
    ('MM','deep','MO','weekend',0.6350000,4),
    ('MM','deep','NT','weekday',0.3600000,8),
    ('MM','deep','NT','weekend',0.4550000,4),
    ('MM','learning','AF','weekday',0.5558552,8),
    ('MM','learning','AF','weekend',0.5529276,4),
    ('MM','learning','EM','weekday',0.6615487,8),
    ('MM','learning','EM','weekend',0.6057743,4),
    ('MM','learning','EV','weekday',0.4705251,8),
    ('MM','learning','EV','weekend',0.5102626,4),
    ('MM','learning','MD','weekday',0.5045090,8),
    ('MM','learning','MD','weekend',0.5272545,4),
    ('MM','learning','MO','weekday',0.6797868,8),
    ('MM','learning','MO','weekend',0.6148934,4),
    ('MM','learning','NT','weekday',0.3684064,8),
    ('MM','learning','NT','weekend',0.4592032,4),
    ('MM','physical','AF','weekday',0.6519281,8),
    ('MM','physical','AF','weekend',0.6009641,4),
    ('MM','physical','EM','weekday',0.6378429,8),
    ('MM','physical','EM','weekend',0.5939214,4),
    ('MM','physical','EV','weekday',0.5139905,8),
    ('MM','physical','EV','weekend',0.5319952,4),
    ('MM','physical','MD','weekday',0.5359438,8),
    ('MM','physical','MD','weekend',0.5429719,4),
    ('MM','physical','MO','weekday',0.6500943,8),
    ('MM','physical','MO','weekend',0.6000472,4),
    ('MM','physical','NT','weekday',0.4460977,8),
    ('MM','physical','NT','weekend',0.4980489,4);

select results_eq(
  $$select count(*) from public.prior_cells where version = 0$$,
  $$select count(*) from expected_prior_cells$$,
  'priors v0: row count matches the spec grid (5 classes x 4 categories x 6 dayparts x 2 day-types)');

select is_empty(
  $$select pc.chronotype_class, pc.category, pc.daypart, pc.day_type
      from public.prior_cells pc
      join expected_prior_cells e using (chronotype_class, category, daypart, day_type)
     where pc.version = 0
       and (abs(pc.mu0 - e.mu0) > 1e-6 or abs(pc.n0 - e.n0) > 1e-9)$$,
  'priors v0: every mu0/n0 matches the spec-derived value (File 04 §3.2 anchor, §3.3 transform + weekend blend)');

select is_empty(
  $$select chronotype_class, category, daypart, day_type from expected_prior_cells
    except
    select chronotype_class, category, daypart, day_type
      from public.prior_cells where version = 0$$,
  'priors v0: no expected cell is missing from the seeded table');

-- ===========================================================================
-- §2 rMEQ→class cutoffs (File 04 §3.1: 22–25 DM · 18–21 MM · 12–17 INT ·
--    8–11 ME · 4–7 DE) — enforced by the profiles CHECK, tested at every boundary
-- ===========================================================================
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a0', 'p4-bounds@test.local');
insert into public.profiles (user_id) values ('00000000-0000-0000-0000-0000000000a0');

create temp table rmeq_boundaries (score int, class text);
insert into rmeq_boundaries values
  (25,'DM'),(22,'DM'),(21,'MM'),(18,'MM'),(17,'INT'),(12,'INT'),(11,'ME'),(8,'ME'),(7,'DE'),(4,'DE');

select lives_ok(
  format($f$update public.profiles
            set rmeq_score = %s, chronotype_class = %L, survey_skipped = false
          where user_id = '00000000-0000-0000-0000-0000000000a0'$f$, score, class),
  format('rMEQ boundary: score %s maps to class %s', score, class))
from rmeq_boundaries order by score desc;

select throws_ok(
  $$update public.profiles set rmeq_score = 22, chronotype_class = 'MM'
    where user_id = '00000000-0000-0000-0000-0000000000a0'$$,
  '23514', null, 'rMEQ boundary: score 22 may not be labeled MM (cutoff is DM)');
select throws_ok(
  $$update public.profiles set rmeq_score = 21, chronotype_class = 'DM'
    where user_id = '00000000-0000-0000-0000-0000000000a0'$$,
  '23514', null, 'rMEQ boundary: score 21 may not be labeled DM (cutoff is MM)');
select throws_ok(
  $$update public.profiles set rmeq_score = 14, chronotype_class = 'INT', survey_skipped = true
    where user_id = '00000000-0000-0000-0000-0000000000a0'$$,
  '23514', null, 'a skipped survey can never carry a score (File 04 §3.1)');
select throws_ok(
  $$update public.profiles
      set rmeq_score = null, chronotype_class = null, survey_skipped = false,
          onboarding_completed_at = now()
    where user_id = '00000000-0000-0000-0000-0000000000a0'$$,
  '23514', null, 'completed onboarding always carries a chronotype class');
select lives_ok(
  $$update public.profiles
      set rmeq_score = null, chronotype_class = 'INT', survey_skipped = true
    where user_id = '00000000-0000-0000-0000-0000000000a0'$$,
  'skipped survey stores class INT with no score (File 04 §3.1)');

-- ===========================================================================
-- §3 instantiation for an answered DM user on the default template
--    (mon–fri [540,1080] ⇒ in-hours dayparts: MO, MD, AF; out: EM, EV @33%, NT;
--     weekend: all out)
-- ===========================================================================
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a1', 'p4-dm@test.local');
insert into public.profiles
  (user_id, working_hours, rmeq_score, chronotype_class, survey_skipped, onboarding_completed_at)
values ('00000000-0000-0000-0000-0000000000a1',
        '{"mon":[540,1080],"tue":[540,1080],"wed":[540,1080],"thu":[540,1080],"fri":[540,1080]}',
        24, 'DM', false, now());

select results_eq(
  $$select count(*) from public.beta_cells
     where user_id = '00000000-0000-0000-0000-0000000000a1'$$,
  $$values (48::bigint)$$,
  'instantiation: 48 cells (4 categories x 6 dayparts x 2 day-types)');

select ok((select bool_and(prior_version = 0) from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'),
  'instantiation: every cell records prior_version 0 (the day-zero bootstrap, File 04 §3.5)');

select ok((select bool_and(succ = 0 and fail = 0) from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'),
  'instantiation: cells start with zero evidence');

-- deep/MO/weekday, in-hours: n0 = 8, mu = .74 ⇒ alpha = 5.92, beta = 2.08
select ok((select abs(alpha0 - 5.92) < 1e-5 and abs(beta0 - 2.08) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'
      and category='deep' and daypart='MO' and day_type='weekday'),
  'DM deep/MO/weekday in-hours: n0=8, mu=.74 => (5.92, 2.08)');

-- deep/EM/weekday, out-of-hours: n0 = 8*0.5 = 4, mu = .78 ⇒ (3.12, 0.88)
select ok((select abs(alpha0 - 3.12) < 1e-5 and abs(beta0 - 0.88) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'
      and category='deep' and daypart='EM' and day_type='weekday'),
  'DM deep/EM/weekday out-of-hours: n0=4, mu=.78 => (3.12, 0.88)');

-- deep/EV/weekday: 60/180 = 33% overlap < 50% ⇒ out-of-hours: n0 = 4, mu = .40 ⇒ (1.6, 2.4)
select ok((select abs(alpha0 - 1.6) < 1e-5 and abs(beta0 - 2.4) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'
      and category='deep' and daypart='EV' and day_type='weekday'),
  'DM deep/EV/weekday at 33% overlap is out-of-hours: n0=4, mu=.40 => (1.6, 2.4)');

-- deep/MO/weekend, out-of-hours: n0 = 4*0.5 = 2, mu = .5*.74+.275 = .645 ⇒ (1.29, 0.71)
select ok((select abs(alpha0 - 1.29) < 1e-5 and abs(beta0 - 0.71) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'
      and category='deep' and daypart='MO' and day_type='weekend'),
  'DM deep/MO/weekend out-of-hours: n0=2, mu=.645 => (1.29, 0.71)');

-- admin/EM/weekday, transformed: mu = sigma(0.45*logit(.78)+0.25) = 0.6941408,
-- out-of-hours n0 = 4 ⇒ (2.7765632, 1.2234368)
select ok((select abs(alpha0 - 2.7765632) < 1e-4 and abs(beta0 - 1.2234368) < 1e-4
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a1'
      and category='admin' and daypart='EM' and day_type='weekday'),
  'DM admin/EM/weekday: logit-affine transform value flows into alpha/beta');

select results_eq(
  $$select cluster_id, method from public.cluster_assignments
     where user_id = '00000000-0000-0000-0000-0000000000a1'$$,
  $$values (0, 'rmeq_seed'::text)$$,
  'seed cluster = rMEQ class (File 04 §3.4): DM => cluster 0');

-- ===========================================================================
-- §4 skipped survey: INT priors at half strength (File 04 §3.1/§3.3; L8 — this
--    IS the wider-exploration mechanism, epsilon never changes)
-- ===========================================================================
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a2', 'p4-skip@test.local');
insert into public.profiles
  (user_id, working_hours, rmeq_score, chronotype_class, survey_skipped, onboarding_completed_at)
values ('00000000-0000-0000-0000-0000000000a2',
        '{"mon":[540,1080],"tue":[540,1080],"wed":[540,1080],"thu":[540,1080],"fri":[540,1080]}',
        null, 'INT', true, now());

-- deep/MO/weekday in-hours skipped: n0 = 8*0.5 = 4, mu = .66 ⇒ (2.64, 1.36)
select ok((select abs(alpha0 - 2.64) < 1e-5 and abs(beta0 - 1.36) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a2'
      and category='deep' and daypart='MO' and day_type='weekday'),
  'skipped: INT deep/MO/weekday n0 halved to 4, mu=.66 => (2.64, 1.36)');

-- deep/MO/weekend out-of-hours skipped: n0 = 4*0.5*0.5 = 1, mu = .5*.66+.275 = .605
select ok((select abs(alpha0 - 0.605) < 1e-5 and abs(beta0 - 0.395) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a2'
      and category='deep' and daypart='MO' and day_type='weekend'),
  'skipped: weekend out-of-hours floor n0=1, mu=.605 => (0.605, 0.395)');

select results_eq(
  $$select cluster_id from public.cluster_assignments
     where user_id = '00000000-0000-0000-0000-0000000000a2'$$,
  $$values (2)$$,
  'skipped survey seeds the INT cluster (2)');

-- ===========================================================================
-- §5 M5 boundary: exactly 50% overlap counts as inside working hours
--    (hours mon–fri [540,930]: AF overlap 840–930 = 90 = 50% of 180 ⇒ IN)
-- ===========================================================================
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a3', 'p4-boundary@test.local');
insert into public.profiles
  (user_id, working_hours, rmeq_score, chronotype_class, survey_skipped, onboarding_completed_at)
values ('00000000-0000-0000-0000-0000000000a3',
        '{"mon":[540,930],"tue":[540,930],"wed":[540,930],"thu":[540,930],"fri":[540,930]}',
        14, 'INT', false, now());

-- deep/AF/weekday at exactly 50%: IN ⇒ n0 = 8, mu = .62 ⇒ (4.96, 3.04)
select ok((select abs(alpha0 - 4.96) < 1e-5 and abs(beta0 - 3.04) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a3'
      and category='deep' and daypart='AF' and day_type='weekday'),
  'M5 boundary: exactly 50% daypart overlap counts as in-hours (n0=8)');

-- deep/EV/weekday zero overlap: OUT ⇒ n0 = 4, mu = .58 ⇒ (2.32, 1.68)
select ok((select abs(alpha0 - 2.32) < 1e-5 and abs(beta0 - 1.68) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a3'
      and category='deep' and daypart='EV' and day_type='weekday'),
  'M5 boundary: zero overlap is out-of-hours (n0=4)');

-- ===========================================================================
-- §6 M5 majority rule across the day-type's days (strict majority, ADR-0005)
-- ===========================================================================
-- 3 of 5 weekdays working ⇒ weekday cells IN; 1 of 2 weekend days ⇒ weekend cells OUT
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a4', 'p4-majority@test.local');
insert into public.profiles
  (user_id, working_hours, rmeq_score, chronotype_class, survey_skipped, onboarding_completed_at)
values ('00000000-0000-0000-0000-0000000000a4',
        '{"mon":[540,1080],"tue":[540,1080],"wed":[540,1080],"sat":[540,1080]}',
        14, 'INT', false, now());

select ok((select abs(alpha0 - 5.28) < 1e-5 from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a4'
      and category='deep' and daypart='MO' and day_type='weekday'),
  'majority: 3 of 5 weekdays working => weekday MO in-hours (n0=8, mu=.66 => 5.28)');

-- weekend MO with sat-only work: 1/2 is not a strict majority ⇒ OUT: n0=2, mu=.605 ⇒ 1.21
select ok((select abs(alpha0 - 1.21) < 1e-5 and abs(beta0 - 0.79) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a4'
      and category='deep' and daypart='MO' and day_type='weekend'),
  'majority: sat-only work is 1/2 weekend days => weekend MO stays out-of-hours (n0=2)');

-- both weekend days working ⇒ weekend cells IN (n0=4)
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a5', 'p4-weekender@test.local');
insert into public.profiles
  (user_id, working_hours, rmeq_score, chronotype_class, survey_skipped, onboarding_completed_at)
values ('00000000-0000-0000-0000-0000000000a5',
        '{"sat":[540,1080],"sun":[540,1080]}', 14, 'INT', false, now());

select ok((select abs(alpha0 - 2.42) < 1e-5 and abs(beta0 - 1.58) < 1e-5
    from public.beta_cells
    where user_id = '00000000-0000-0000-0000-0000000000a5'
      and category='deep' and daypart='MO' and day_type='weekend'),
  'majority: 2/2 weekend days working => weekend MO in-hours (n0=4, mu=.605 => 2.42)');

-- ===========================================================================
-- §7 idempotency + invariant 5 (priors never overwrite evidence)
-- ===========================================================================
select results_eq(
  $$select public.instantiate_user_priors('00000000-0000-0000-0000-0000000000a1')$$,
  $$values (0)$$,
  'idempotency: re-instantiating an instantiated user inserts nothing');

insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a7', 'p4-evidence@test.local');
insert into public.profiles (user_id, working_hours, rmeq_score, chronotype_class)
values ('00000000-0000-0000-0000-0000000000a7', '{"mon":[540,1080]}', 16, 'INT');
-- pre-existing evidence in one cell (as the service would have written it)
insert into public.beta_cells
  (user_id, category, daypart, day_type, succ, fail, alpha0, beta0, prior_version)
values ('00000000-0000-0000-0000-0000000000a7', 'deep', 'MO', 'weekday', 5, 3, 99, 1, 0);
-- pre-existing ALS cluster assignment
insert into public.cluster_assignments (user_id, cluster_id, method)
values ('00000000-0000-0000-0000-0000000000a7', 7, 'als_foldin');

update public.profiles set onboarding_completed_at = now()
 where user_id = '00000000-0000-0000-0000-0000000000a7';

select results_eq(
  $$select count(*) from public.beta_cells
     where user_id = '00000000-0000-0000-0000-0000000000a7'$$,
  $$values (48::bigint)$$,
  'invariant 5: instantiation fills only the 47 missing cells around existing evidence');

select results_eq(
  $$select succ::int, fail::int, alpha0::int from public.beta_cells
     where user_id = '00000000-0000-0000-0000-0000000000a7'
       and category='deep' and daypart='MO' and day_type='weekday'$$,
  $$values (5, 3, 99)$$,
  'invariant 5: the cell with evidence is untouched');

select results_eq(
  $$select cluster_id, method from public.cluster_assignments
     where user_id = '00000000-0000-0000-0000-0000000000a7'$$,
  $$values (7, 'als_foldin'::text)$$,
  'invariant 5: an ALS fold-in assignment is never overwritten by the rMEQ seed');

-- ===========================================================================
-- §8 trigger timing: fires exactly when onboarding_completed_at first lands
-- ===========================================================================
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a6', 'p4-timing@test.local');
insert into public.profiles (user_id, working_hours, rmeq_score, chronotype_class)
values ('00000000-0000-0000-0000-0000000000a6', '{"mon":[540,1080]}', 15, 'INT');

select results_eq(
  $$select count(*) from public.beta_cells
     where user_id = '00000000-0000-0000-0000-0000000000a6'$$,
  $$values (0::bigint)$$,
  'trigger: no cells before onboarding completes');

update public.profiles set onboarding_completed_at = now()
 where user_id = '00000000-0000-0000-0000-0000000000a6';

select results_eq(
  $$select count(*) from public.beta_cells
     where user_id = '00000000-0000-0000-0000-0000000000a6'$$,
  $$values (48::bigint)$$,
  'trigger: completing onboarding instantiates the cells');

-- ===========================================================================
-- §9 the production path: an authenticated client inserting its own completed
--    profile gets cells via the SECURITY DEFINER trigger, but can neither call
--    the function directly nor write model state (invariant 1, NFR-S1)
-- ===========================================================================
insert into auth.users (id, email)
values ('00000000-0000-0000-0000-0000000000a8', 'p4-client@test.local');

set local role authenticated;
set local request.jwt.claims to '{"sub":"00000000-0000-0000-0000-0000000000a8","role":"authenticated"}';

select lives_ok(
  $$insert into public.profiles
      (user_id, working_hours, rmeq_score, chronotype_class, survey_skipped, onboarding_completed_at)
    values ('00000000-0000-0000-0000-0000000000a8', '{"mon":[540,1080]}', 20, 'MM', false, now())$$,
  'client path: authenticated user inserts their own completed profile through RLS');

select results_eq(
  $$select count(*) from public.beta_cells
     where user_id = '00000000-0000-0000-0000-0000000000a8'$$,
  $$values (48::bigint)$$,
  'client path: the trigger instantiated cells despite the caller lacking beta_cells writes');

select results_eq(
  $$select count(*) from public.beta_cells$$,
  $$values (48::bigint)$$,
  'RLS: the client sees only its own cells, none of the other fixtures');

select throws_ok(
  $$select public.instantiate_user_priors('00000000-0000-0000-0000-0000000000a8')$$,
  '42501', null,
  'invariant 1: authenticated clients cannot execute instantiate_user_priors');

select throws_ok(
  $$insert into public.beta_cells
      (user_id, category, daypart, day_type, succ, fail, alpha0, beta0, prior_version)
    values ('00000000-0000-0000-0000-0000000000a8', 'deep', 'MO', 'weekday', 0, 0, 1, 1, 0)$$,
  '42501', null,
  'invariant 1: authenticated clients cannot insert beta_cells rows');

select throws_ok(
  $$update public.beta_cells set succ = 99
     where user_id = '00000000-0000-0000-0000-0000000000a8'$$,
  '42501', null,
  'invariant 1: authenticated clients cannot update beta_cells rows');

reset role;

select * from finish();
rollback;
