import { assertAlmostEquals, assertEquals } from '@std/assert';
import { bucketFromId } from './contexts.ts';
import { FEATURE_NAMES, featureVector, urgencyTerm } from './features.ts';

// Reference vectors generated by the service's `features.feature_vector` (features.py) on
// 2026-08-26 for the same inputs — the arm-A snapshot must equal the arm-B snapshot bit for bit.
const CASES = [
  {
    bucket: 'AF.wd.fatigued',
    value: 3,
    estMinutes: 90,
    splittable: true,
    uTicks: 10,
    postponeCount: 2,
    cellMean: 0.6,
    cellSd: 0.2,
    precedingLoadMinutes: 120,
    expected: [
      1,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      1,
      1,
      0.7288573971628706,
      1,
      0.5352614285189903,
      0.4,
      0.6,
      0.2,
      0.6666666666666666,
    ],
  },
  {
    bucket: 'EM.we',
    value: 1,
    estMinutes: 15,
    splittable: false,
    uTicks: null,
    postponeCount: 7,
    cellMean: 0.5,
    cellSd: 0.2236,
    precedingLoadMinutes: 0,
    expected: [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0.4386368681271087, 0, 0, 1, 0.5, 0.2236, 0],
  },
  {
    bucket: 'NT.wd',
    value: 2,
    estMinutes: 600,
    splittable: true,
    uTicks: 0,
    postponeCount: 0,
    cellMean: 0.31,
    cellSd: 0.11,
    precedingLoadMinutes: 400,
    expected: [1, 0, 0, 0, 0, 0, 1, 0, 0, 0.5, 1, 1, 1, 0, 0.31, 0.11, 1],
  },
];

Deno.test('x_{τ,c} equals the service reference vectors (specs/07 §3.2.4 order, d = 17)', () => {
  assertEquals(FEATURE_NAMES.length, 17);
  for (const c of CASES) {
    const x = featureVector({ ...c, bucket: bucketFromId(c.bucket) });
    assertEquals(x.length, 17);
    for (let i = 0; i < 17; i++) {
      assertAlmostEquals(x[i], c.expected[i], 1e-12, `${c.bucket} feature ${FEATURE_NAMES[i]}`);
    }
  }
});

Deno.test('urgency e^{−u/η}: 0 without a deadline, 1 at the deadline, clamps negative u', () => {
  assertEquals(urgencyTerm(null), 0);
  assertEquals(urgencyTerm(0), 1);
  assertEquals(urgencyTerm(-3), 1);
  assertAlmostEquals(urgencyTerm(16), Math.exp(-1), 1e-12);
});
