/**
 * H1 symmetry, mechanically: the Deno grid / φ / F_τ / eligibility reproduce the service's
 * output for the same requests. The fixture is generated by the Python side
 * (`services/recsys/scripts/gen_grid_parity.py`) and pinned there by
 * `tests/test_grid_parity_fixture.py`; a drift on either side fails one of the two suites.
 */
import { assertEquals } from '@std/assert';
import { bucketsForGrid } from './contexts.ts';
import { eligibleTasks, type ExperimentCandidate } from './exploration.ts';
import {
  buildGrid,
  feasibleStarts,
  type Horizon,
  runLengths,
  tickCeil,
  tickFloor,
  type WorkingHours,
} from './grid.ts';

interface FixtureTask {
  id: string;
  duration: number;
  earliest_tick: number | null;
  deadline_tick: number | null;
  feasible_starts: number[];
  feasible_bucket_ids: string[];
}
interface FixtureCase {
  input: {
    name: string;
    plan_date: string;
    horizon: Horizon;
    timezone: string;
    working_hours: Record<string, [number, number]>;
    sleep_window: [number, number] | null;
    busy: Array<{ start: string; end: string }>;
    now: string | null;
    tasks: Array<
      {
        id: string;
        est_minutes: number;
        earliest: string | null;
        deadline: string | null;
        critical: boolean;
      }
    >;
  };
  n_ticks: number;
  origin: string;
  tick_minutes: number;
  local_minute: number[];
  weekday: number[];
  day_index: number[];
  workable: number[];
  occupied: number[];
  buckets: Array<string | null>;
  tasks: FixtureTask[];
  eligible: string[];
}

const fixture = JSON.parse(
  await Deno.readTextFile(new URL('./testdata/grid_parity.json', import.meta.url)),
) as {
  cases: FixtureCase[];
};

for (const c of fixture.cases) {
  Deno.test(`grid/φ/F_τ/eligibility parity with the service: ${c.input.name}`, () => {
    const grid = buildGrid({
      planDate: c.input.plan_date,
      horizon: c.input.horizon,
      timezone: c.input.timezone,
      workingHours: c.input.working_hours as WorkingHours,
      sleepWindow: c.input.sleep_window,
      busy: c.input.busy.map((b) => ({ startMs: Date.parse(b.start), endMs: Date.parse(b.end) })),
      nowMs: c.input.now === null ? null : Date.parse(c.input.now),
    });
    assertEquals(grid.nTicks, c.n_ticks);
    assertEquals(new Date(grid.originMs).toISOString().replace('.000Z', 'Z'), c.origin);
    assertEquals(grid.tickMinutes, c.tick_minutes);
    assertEquals(Array.from(grid.localMinute), c.local_minute);
    assertEquals(Array.from(grid.weekday), c.weekday);
    assertEquals(Array.from(grid.dayIndex), c.day_index);
    const idx = (arr: Uint8Array) =>
      Array.from(arr).map((v, k) => (v ? k : -1)).filter((k) => k >= 0);
    assertEquals(idx(grid.workable), c.workable);
    assertEquals(idx(grid.occupied), c.occupied);
    assertEquals(
      bucketsForGrid(grid, grid.occupied).map((b) => (b === null ? null : b.id)),
      c.buckets,
    );
    const r = runLengths(grid);
    const buckets = bucketsForGrid(grid, grid.occupied);
    const candidates: ExperimentCandidate[] = [];
    for (const t of c.input.tasks) {
      const expected = c.tasks.find((x) => x.id === t.id) as FixtureTask;
      const duration = Math.max(1, Math.ceil(t.est_minutes / 15));
      const earliest = t.earliest === null ? null : tickCeil(grid, Date.parse(t.earliest));
      const deadline = t.deadline === null ? null : tickFloor(grid, Date.parse(t.deadline));
      assertEquals([duration, earliest, deadline], [
        expected.duration,
        expected.earliest_tick,
        expected.deadline_tick,
      ]);
      const starts = feasibleStarts(grid, { duration, earliest, deadline, runLengths: r });
      assertEquals(starts, expected.feasible_starts);
      const ids = [
        ...new Set(starts.map((k) => buckets[k]?.id).filter((x): x is string => x !== undefined)),
      ].sort();
      assertEquals(ids, expected.feasible_bucket_ids);
      candidates.push({
        taskId: t.id,
        duration,
        critical: t.critical,
        pinned: false,
        feasibleBucketIds: ids,
      });
    }
    assertEquals(eligibleTasks(candidates), c.eligible);
  });
}
