/**
 * H1 symmetry, mechanically: the Deno grid / φ / F_τ / representative ticks / feature snapshot /
 * eligibility reproduce the service's own `_prepare` output for the same requests. The fixture is
 * generated by the Python side (`services/recsys/scripts/gen_grid_parity.py`, via
 * `hourwell_recsys.parity_fixture`) and pinned there by `tests/test_grid_parity_fixture.py`; a
 * drift on either side fails one of the two suites. Cases cover DST days (Kyiv spring/fall, New
 * York fall), a `now` inside the horizon, busy blocks with buffers, and a pinned task (φ fatigue
 * and feature 17 read pinned occupancy).
 */
import { assertAlmostEquals, assertEquals } from '@std/assert';
import { eligibleTasks, type ExperimentCandidate } from './exploration.ts';
import { prepareHeuristic } from './heuristic.ts';
import type { Horizon } from './grid.ts';
import type { ServicePlanRequest, ServiceTaskIn } from './types.ts';

interface FixtureTask {
  id: string;
  unplaceable: boolean;
  duration?: number;
  critical?: boolean;
  earliest_tick?: number | null;
  deadline_tick?: number | null;
  pinned_tick?: number | null;
  feasible_starts?: number[];
  chunk_starts?: number[];
  feasible_bucket_ids?: string[];
  rep_ticks?: Record<string, number>;
  features?: Record<string, number[]>;
}
interface FixtureCase {
  input: {
    name: string;
    plan_date: string;
    horizon: Horizon;
    timezone: string;
    working_hours: Record<string, [number, number]>;
    sleep_window: [number, number] | null;
    busy: Array<{ start: string; end: string }>;
    now: string | null;
    tasks: ServiceTaskIn[];
  };
  n_ticks: number;
  origin: string;
  tick_minutes: number;
  local_minute: number[];
  weekday: number[];
  day_index: number[];
  workable: number[];
  occupied: number[];
  buckets: Array<string | null>;
  tasks: FixtureTask[];
  eligible: string[];
}

const fixture = JSON.parse(
  await Deno.readTextFile(new URL('./testdata/grid_parity.json', import.meta.url)),
) as { cases: FixtureCase[] };

const FIXED_NOW_MS = Date.parse('2026-01-01T00:00:00Z'); // the generator's read_at when `now` is null

for (const c of fixture.cases) {
  Deno.test(`parity with the service's _prepare: ${c.input.name}`, () => {
    const req: ServicePlanRequest = {
      user_id: '00000000-0000-4000-8000-00000000f1de',
      plan_date: c.input.plan_date,
      horizon: c.input.horizon,
      timezone: c.input.timezone,
      working_hours: c.input.working_hours,
      sleep_window: c.input.sleep_window,
      busy: c.input.busy,
      tasks: c.input.tasks,
      previous_assignments: [],
      settings: { epsilon: 1, top_m: 4, policy: 'ts' },
      arm: null,
      now: c.input.now,
    };
    const nowMs = c.input.now === null ? FIXED_NOW_MS : Date.parse(c.input.now);
    const prep = prepareHeuristic(req, { nowMs, cells: [] });
    const grid = prep.grid;
    assertEquals(grid.nTicks, c.n_ticks);
    assertEquals(new Date(grid.originMs).toISOString().replace('.000Z', 'Z'), c.origin);
    assertEquals(grid.tickMinutes, c.tick_minutes);
    assertEquals(Array.from(grid.localMinute), c.local_minute);
    assertEquals(Array.from(grid.weekday), c.weekday);
    assertEquals(Array.from(grid.dayIndex), c.day_index);
    const idx = (arr: Uint8Array) =>
      Array.from(arr).map((v, k) => (v ? k : -1)).filter((k) => k >= 0);
    assertEquals(idx(grid.workable), c.workable);
    assertEquals(idx(prep.occupancy), c.occupied, 'a-priori occupancy = fixed events ∪ pinned');
    assertEquals(prep.buckets.map((b) => (b === null ? null : b.id)), c.buckets);

    const candidates: ExperimentCandidate[] = [];
    for (const expected of c.tasks) {
      const tid = expected.id;
      if (expected.unplaceable && expected.duration === undefined) {
        assertEquals(prep.unplaceable.has(tid), true, `${tid} unplaceable`);
        continue;
      }
      const s = prep.specs.get(tid);
      if (s === undefined) throw new Error(`spec missing for ${tid}`);
      assertEquals(
        [s.duration, s.critical, s.earliestTick, s.deadlineTick, s.pinnedTick],
        [
          expected.duration,
          expected.critical,
          expected.earliest_tick,
          expected.deadline_tick,
          expected.pinned_tick,
        ],
        `${tid} spec`,
      );
      assertEquals(prep.unplaceable.has(tid), expected.unplaceable, `${tid} unplaceable flag`);
      assertEquals(prep.fullStarts.get(tid), expected.feasible_starts, `${tid} F_τ`);
      assertEquals(prep.chunkStarts.get(tid), expected.chunk_starts, `${tid} chunk starts`);
      const bucketIds = [
        ...new Set(
          (prep.fullStarts.get(tid) ?? []).map((k) => prep.buckets[k]?.id).filter((
            x,
          ): x is string => x !== undefined),
        ),
      ].sort();
      assertEquals(bucketIds, expected.feasible_bucket_ids, `${tid} A(x)`);
      const reps = Object.fromEntries([...(prep.repTicks.get(tid) ?? new Map())].sort());
      assertEquals(reps, expected.rep_ticks, `${tid} representative ticks k*`);
      for (const [bucketId, vec] of Object.entries(expected.features ?? {})) {
        const x = prep.featuresFor(tid, bucketId);
        assertEquals(x.length, 17);
        for (let i = 0; i < 17; i++) {
          assertAlmostEquals(x[i], vec[i], 1e-12, `${tid} ${bucketId} feature ${i}`);
        }
      }
      if (!expected.unplaceable) {
        candidates.push({
          taskId: tid,
          duration: s.duration,
          critical: s.critical,
          pinned: s.pinnedTick !== null,
          feasibleBucketIds: bucketIds,
        });
      }
    }
    assertEquals(eligibleTasks(candidates), c.eligible);
  });
}
