/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Labels
         * @description P9 belief labels (FR-33/FR-41, ADR-0013): store + full rebuild (invariant 6).
         */
        post: operations["labels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Preview */
        post: operations["parsePreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdherenceWeek */
        AdherenceWeek: {
            /** Par */
            par: number;
            /** Week */
            week: string;
        };
        /** Affinity */
        Affinity: {
            /** Confidence */
            confidence: number;
            /** Key */
            key: string;
            /** Label */
            label?: ("correct" | "incorrect" | "none") | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Personal
             * @default false
             */
            personal: boolean;
            /** State Ref */
            state_ref: string;
        };
        /** Assignment */
        Assignment: {
            /** Chunk Index */
            chunk_index: number;
            /** Confidence */
            confidence: number;
            /** Context Bucket */
            context_bucket: string;
            /** Experiment Top M */
            experiment_top_m?: string[] | null;
            /** Features */
            features: number[];
            /** Is Experiment */
            is_experiment: boolean;
            /** Propensity */
            propensity: number | null;
            /** Q Hat */
            q_hat: number;
            /** Rationale Key */
            rationale_key: string;
            /** Rationale Params */
            rationale_params: {
                [key: string]: unknown;
            };
            /**
             * Slot End
             * Format: date-time
             */
            slot_end: string;
            /**
             * Slot Start
             * Format: date-time
             */
            slot_start: string;
            /** Task Id */
            task_id: string;
        };
        /**
         * Belief
         * @description FR-41 "What Hourwell believes about you": per (category, day_type) the daypart the
         *     posterior currently favours — present even below the affinity threshold, so the user always
         *     has something to confirm or correct (FR-33 "actually, I am a morning person").
         */
        Belief: {
            /** Affinity */
            affinity: boolean;
            /**
             * Category
             * @enum {string}
             */
            category: "deep" | "admin" | "physical" | "learning";
            /** Confidence */
            confidence: number;
            /**
             * Day Type
             * @enum {string}
             */
            day_type: "weekday" | "weekend";
            /** Daypart */
            daypart: string;
            /** Factor */
            factor: number;
            /** Label */
            label?: ("correct" | "incorrect" | "none") | null;
            /** Mean */
            mean: number;
            /** N Effective */
            n_effective: number;
            /** Personal */
            personal: boolean;
            /** State Ref */
            state_ref: string;
        };
        /**
         * BeliefLabel
         * @description One client `belief_label` fact (P9, ADR-0013); `id` = the event op_id.
         */
        BeliefLabel: {
            /** Id */
            id: string;
            /**
             * Label
             * @enum {string}
             */
            label: "correct" | "incorrect" | "none";
            /**
             * Labeled At
             * Format: date-time
             */
            labeled_at: string;
            /** State Ref */
            state_ref: string;
        };
        /** BusyInterval */
        BusyInterval: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Tuples */
            tuples: components["schemas"]["FeedbackTuple"][];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Rebuilt */
            rebuilt: boolean;
            /** Skipped Excluded */
            skipped_excluded: number;
            /** State Version */
            state_version: number;
            /** Updated */
            updated: number;
        };
        /** FeedbackTuple */
        FeedbackTuple: {
            /**
             * Attributed At
             * Format: date-time
             */
            attributed_at: string;
            /**
             * Category
             * @enum {string}
             */
            category: "deep" | "admin" | "physical" | "learning";
            /**
             * Correction
             * @default false
             */
            correction: boolean;
            /**
             * Excluded
             * @default false
             */
            excluded: boolean;
            /** Excluded Reason */
            excluded_reason?: string | null;
            /** Features */
            features: number[];
            /**
             * Kind
             * @default outcome
             * @enum {string}
             */
            kind: "outcome" | "override_out" | "override_in";
            /**
             * Reason
             * @enum {string}
             */
            reason: "completed" | "partial" | "off_slot" | "lapsed" | "skipped" | "rejected" | "override_out" | "override_in";
            /** Recommendation Id */
            recommendation_id: string;
            /** Reward */
            reward: number;
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** Arch */
            arch: string;
            /** Build */
            build: string;
            /** Model Versions */
            model_versions: {
                [key: string]: string | null;
            };
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Storage
             * @enum {string}
             */
            storage: "postgres" | "memory";
            /** Uptime S */
            uptime_s: number;
        };
        /** HeatmapCell */
        HeatmapCell: {
            /**
             * Category
             * @enum {string}
             */
            category: "deep" | "admin" | "physical" | "learning";
            /** Ci */
            ci: [
                number,
                number
            ];
            /**
             * Day Type
             * @enum {string}
             */
            day_type: "weekday" | "weekend";
            /** Daypart */
            daypart: string;
            /** Mean */
            mean: number;
            /** N Effective */
            n_effective: number;
            /**
             * Personal
             * @default false
             */
            personal: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Infeasible */
        Infeasible: {
            /** Options */
            options: components["schemas"]["TradeOffOption"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Adherence */
            adherence: components["schemas"]["AdherenceWeek"][];
            /** Affinities */
            affinities: components["schemas"]["Affinity"][];
            /** Beliefs */
            beliefs?: components["schemas"]["Belief"][];
            /** Heatmap */
            heatmap: components["schemas"]["HeatmapCell"][];
            /** Labels */
            labels?: components["schemas"]["LabelState"][];
            /**
             * Learning Mode
             * @default true
             */
            learning_mode: boolean;
        };
        /** LabelsRequest */
        LabelsRequest: {
            /** Labels */
            labels: components["schemas"]["BeliefLabel"][];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** LabelsResponse */
        LabelsResponse: {
            /** Applied */
            applied: number;
            /** Rebuilt */
            rebuilt: boolean;
            /** State Version */
            state_version: number;
        };
        /** LabelState */
        LabelState: {
            /**
             * Label
             * @enum {string}
             */
            label: "correct" | "incorrect" | "none";
            /**
             * Labeled At
             * Format: date-time
             */
            labeled_at: string;
            /** State Ref */
            state_ref: string;
        };
        /** ParsePreviewRequest */
        ParsePreviewRequest: {
            /**
             * Now
             * Format: date-time
             */
            now: string;
            /** Text */
            text: string;
            /** Timezone */
            timezone: string;
        };
        /** ParsePreviewResponse */
        ParsePreviewResponse: {
            /** Ambiguities */
            ambiguities: string[];
            /** Category Guess */
            category_guess: ("deep" | "admin" | "physical" | "learning") | null;
            /** Deadline */
            deadline: string | null;
            /** Est Minutes */
            est_minutes: number | null;
            /** Title */
            title: string;
        };
        /** PlanRequest */
        PlanRequest: {
            /** Arm */
            arm?: ("A" | "B") | null;
            /** Busy */
            busy?: components["schemas"]["BusyInterval"][];
            /**
             * Horizon
             * @default day
             * @enum {string}
             */
            horizon: "day" | "week";
            /** Now */
            now?: string | null;
            /**
             * Plan Date
             * Format: date
             */
            plan_date: string;
            /** Previous Assignments */
            previous_assignments?: components["schemas"]["PreviousAssignment"][];
            settings?: components["schemas"]["PlanSettings"];
            /** Sleep Window */
            sleep_window?: [
                number,
                number
            ] | null;
            /** Tasks */
            tasks: components["schemas"]["TaskIn"][];
            /** Timezone */
            timezone: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Working Hours */
            working_hours: {
                [key: string]: [
                    number,
                    number
                ];
            };
        };
        /** PlanResponse */
        PlanResponse: {
            /** Assignments */
            assignments: components["schemas"]["Assignment"][];
            /**
             * Engine
             * @default learned
             * @constant
             */
            engine: "learned";
            infeasible: components["schemas"]["Infeasible"] | null;
            /** Model Version */
            model_version: string;
            /** Solver Status */
            solver_status: string;
            telemetry: components["schemas"]["Telemetry"];
            /** Unplaced */
            unplaced: components["schemas"]["Unplaced"][];
        };
        /** PlanSettings */
        PlanSettings: {
            /**
             * Epsilon
             * @default 1
             */
            epsilon: number;
            /**
             * Policy
             * @default ts
             * @enum {string}
             */
            policy: "ts" | "linucb" | "heuristic-shadow";
            /** Seed */
            seed?: number | null;
            /**
             * Top M
             * @default 4
             */
            top_m: number;
        };
        /** PreviousAssignment */
        PreviousAssignment: {
            /**
             * Chunk Index
             * @default 0
             */
            chunk_index: number;
            /**
             * Slot Start
             * Format: date-time
             */
            slot_start: string;
            /** Task Id */
            task_id: string;
        };
        /** TaskIn */
        TaskIn: {
            /**
             * Category
             * @enum {string}
             */
            category: "deep" | "admin" | "physical" | "learning";
            /** Deadline */
            deadline?: string | null;
            /** Earliest Start */
            earliest_start?: string | null;
            /** Est Minutes */
            est_minutes: number;
            /** Id */
            id: string;
            /** Pinned Start */
            pinned_start?: string | null;
            /**
             * Postpone Count
             * @default 0
             */
            postpone_count: number;
            /**
             * Splittable
             * @default false
             */
            splittable: boolean;
            /** Value */
            value: number;
        };
        /** Telemetry */
        Telemetry: {
            /** Build Ms */
            build_ms: number;
            /** Degradation */
            degradation: ("coarse_30min" | "day_by_day") | null;
            /** Experiment Drawn */
            experiment_drawn: boolean;
            /** Experiment Dropped */
            experiment_dropped: boolean;
            /** Fragmentation Penalty */
            fragmentation_penalty: number;
            /** Hints */
            hints: number;
            /** Literals */
            literals: number;
            /** N Ticks */
            n_ticks: number;
            /** Objective */
            objective: number;
            /**
             * Policy
             * @enum {string}
             */
            policy: "ts" | "linucb" | "heuristic-shadow";
            /** Rng Seed */
            rng_seed: number;
            /** Run Length Penalty */
            run_length_penalty: number;
            /** Solve Ms */
            solve_ms: number;
            /** Solves */
            solves: number;
            /** Tick Minutes */
            tick_minutes: number;
            /** Total Ms */
            total_ms: number;
        };
        /** TradeOffOption */
        TradeOffOption: {
            /** Consequence */
            consequence: {
                [key: string]: number | string;
            };
            /** Delta Minutes */
            delta_minutes?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "drop" | "shrink" | "move_past_deadline" | "unpin";
            /** Task Id */
            task_id: string;
        };
        /** Unplaced */
        Unplaced: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "no_feasible_start" | "deferred" | "infeasible";
            /** Task Id */
            task_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAdherenceWeek = components['schemas']['AdherenceWeek'];
export type SchemaAffinity = components['schemas']['Affinity'];
export type SchemaAssignment = components['schemas']['Assignment'];
export type SchemaBelief = components['schemas']['Belief'];
export type SchemaBeliefLabel = components['schemas']['BeliefLabel'];
export type SchemaBusyInterval = components['schemas']['BusyInterval'];
export type SchemaFeedbackRequest = components['schemas']['FeedbackRequest'];
export type SchemaFeedbackResponse = components['schemas']['FeedbackResponse'];
export type SchemaFeedbackTuple = components['schemas']['FeedbackTuple'];
export type SchemaHealthzResponse = components['schemas']['HealthzResponse'];
export type SchemaHeatmapCell = components['schemas']['HeatmapCell'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaInfeasible = components['schemas']['Infeasible'];
export type SchemaInsightsResponse = components['schemas']['InsightsResponse'];
export type SchemaLabelsRequest = components['schemas']['LabelsRequest'];
export type SchemaLabelsResponse = components['schemas']['LabelsResponse'];
export type SchemaLabelState = components['schemas']['LabelState'];
export type SchemaParsePreviewRequest = components['schemas']['ParsePreviewRequest'];
export type SchemaParsePreviewResponse = components['schemas']['ParsePreviewResponse'];
export type SchemaPlanRequest = components['schemas']['PlanRequest'];
export type SchemaPlanResponse = components['schemas']['PlanResponse'];
export type SchemaPlanSettings = components['schemas']['PlanSettings'];
export type SchemaPreviousAssignment = components['schemas']['PreviousAssignment'];
export type SchemaTaskIn = components['schemas']['TaskIn'];
export type SchemaTelemetry = components['schemas']['Telemetry'];
export type SchemaTradeOffOption = components['schemas']['TradeOffOption'];
export type SchemaUnplaced = components['schemas']['Unplaced'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    feedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    insights: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    labels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parsePreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParsePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
